### Vector Arithmetic
---

A vector is a tuple of one or more values called scalars.

Vectors are often represented using a lowercase character such as v; for example:

$$ v = \begin{pmatrix}
v_1, & v_2, & v_3\\
\end{pmatrix}$$

Where v1, v2, v3 are scalar values

Vectors are also shown using a vertical representation or a column; for example:

$$ v = \begin{pmatrix}
v_1 \\ v_2 \\ v_3\\
\end{pmatrix}$$

We can represent a vector in Python as a NumPy array...

In [2]:
import numpy as np

In [3]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

#### Vector Addition

Two vectors of equal length can be added together to create a new third vector.

$$ \large{c = a + b}$$

The new vector has the same length as the other two vectors. 

Each element of the new vector is calculated as the addition of the elements of the other vectors at the same index; 

$$ \large{c + (a_1 + b_1,\, a_2 + b_2,\, a_3 + b_3)} $$

We can add vectors directly in Python by adding NumPy arrays.

In [5]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3]) 
c = a + b
c

array([2, 4, 6])

#### Vector Subtraction

One vector can be subtracted from another vector of equal length to create a new third vector. 

$$ \large{c = a - b}$$ 
  
As with addition, the new vector has the same length as the parent vectors 

Each element of the new vector is calculated as the subtraction of the elements at the same indices. 

$$ \large{c = (a_1 - b_1, \,a_2 - b_2, \, a_3 - b_3)} $$

In python...

In [8]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([0.5, 0.5, 0.5])
c = a - b
c

array([0.5, 1.5, 2.5])

#### Vector Multiplication

Two vectors of equal length can be multiplied together.

$$ \large{c = a \times b} $$

As with addition and subtraction, this operation is performed element-wise to result in a

new vector of the same length.

$$ \large{c = (a_1 \times b_1, \, a_2 \times b_2, \, a_3 \times b_3)} $$

In [9]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3]) 
c = a * b
c

array([1, 4, 9])

#### Vector Division

Two vectors of equal length can be divided.
  
$$ \large{c = \frac{a}{b}} $$

As with other arithmetic operations, this operation is performed element-wise

$$ \large{c = \begin{pmatrix}
\frac{a_1}{b_1}, & \frac{a_2}{b_2}, & \frac{a_3}{a_4}\\
\end{pmatrix}}$$


In [11]:
a = np.array([2, 4, 6])
b = np.array([1, 2, 3]) 
c = a / b
c

array([2., 2., 2.])

#### Vector Dot Product

We can calculate the sum of the multiplied elements of two vectors of the same length to give a scalar. 

This is called the dot product, named because of the dot operator used when describing the operation.

$$ \large{c = a \cdot b} $$
 
The dot product is calculated as follows:
  
$$ \large{c = (a_1b_1 + a_2b_2 + a_3b_3)} $$

We can calculate the dot product between two vectors in Python using the dot() function on a NumPy array.

In [3]:
a = np.array([2, 4, 6])
b = np.array([1, 2, 3]) 
c = a.dot(b)
c

28

#### Vector-Scalar Multiplication

A vector can be multiplied by a scalar, in effect scaling the magnitude of the vector. 

To keep notation simple, we will use lowercase s to represent the scalar value.

$$ \large{c = s \times v }$$

The multiplication is performed on each element of the vector to result in a new scaled vector of the same length.

$$ \large{c = (s \times v_1, s \times v_2, s \times v_3)} $$

We can perform this operation directly with the NumPy array.

In [4]:
v = np.array([2, 4, 6])
s = 2
c = s * v
c

array([ 4,  8, 12])

### Vector Norms
---

Calculating the size or length of a vector is often required either

The length of the vector is referred to as the vector norm or the vector’s magnitude.

It's calculated using a measure that summarizes the distance of the vector from the origin of the vector space.

For example, the origin of a vector space for a vector with 3 elements is (0, 0, 0). 

#### Vector $L^1$ Norm

The length of a vector can be calculated using the $L^1$ norm. 

The notation for the L1 norm of a vector is $||v||_1$, where 1 is a subscript. 

As such, this length is sometimes called the taxicab norm or the Manhattan norm.

$$ \large{ L_1(v) = ||v||_1 } $$

The L1 norm is calculated as the sum of the absolute vector values

$$ \large{ ||v||_1 = |a_1| + |a_2| + |a_3|} $$



In [5]:
a  = np.array([1, 2, 3])
L1 = np.linalg.norm(a, 1)
L1

6.0

#### Vector $L^2$ Norm


The $L^2$ norm calculates the distance of the vector coordinate from the origin of the vector space. 

$$ \large{ L^2(v) = ||v||_2 } $$

As such, it is also known as the Euclidean norm as it is calculated as the Euclidean distance from the origin. 

The $L^2$ norm is calculated as the square root of the sum of the squared vector values.

$$ \large{ ||v||_2 = \sqrt{ a^2_1 + a^2_2 + a^2_3 }} $$

In [7]:
a  = np.array([1, 2, 3])
L2 = np.linalg.norm(a)
round(L2, 3)

3.742

#### Vector Max Norm

The notation for max norm is $||v||_inf$, where inf is a subscript.

$$ \large{ L^{inf} (v) = ||v||_inf } $$

The max norm is calculated as returning the maximum absolute value of the vector, hence the name.

$$ \large{ ||v||_{inf} = max(|a_1|, |a_2|, |a_3|) } $$

In [ ]:
a  = np.array([1, 2, 3])
m = np.linalg.norm(a, inf)
