### Vector Arithmetic
---

A vector is a tuple of one or more values called scalars.

Vectors are often represented using a lowercase character such as v; for example:

$$ v = \begin{pmatrix}
v_1, & v_2, & v_3\\
\end{pmatrix}$$

Where v1, v2, v3 are scalar values

Vectors are also shown using a vertical representation or a column; for example:

$$ v = \begin{pmatrix}
v_1 \\ v_2 \\ v_3\\
\end{pmatrix}$$

We can represent a vector in Python as a NumPy array...

In [6]:
import numpy as np

In [3]:
v = np.array([1, 2, 3])
v

array([1, 2, 3])

#### Vector Addition

Two vectors of equal length can be added together to create a new third vector.

$$ \large{c = a + b}$$

The new vector has the same length as the other two vectors. 

Each element of the new vector is calculated as the addition of the elements of the other vectors at the same index; 

$$ \large{c = (a_1 + b_1,\, a_2 + b_2,\, a_3 + b_3)} $$

We can add vectors directly in Python by adding NumPy arrays.

In [5]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3]) 
c = a + b
c

array([2, 4, 6])

#### Vector Subtraction

One vector can be subtracted from another vector of equal length to create a new third vector. 

$$ \large{c = a − b}$$ 
  
As with addition, the new vector has the same length as the parent vectors 

Each element of the new vector is calculated as the subtraction of the elements at the same indices. 

$$ \large{c=(a_1 − b_1, \,a_2 − b_2, \, a_3 − b_3)} $$

In python...

In [8]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([0.5, 0.5, 0.5])
c = a - b
c

array([0.5, 1.5, 2.5])

#### Vector Multiplication

Two vectors of equal length can be multiplied together.

$$ \large{c = a × b} $$

As with addition and subtraction, this operation is performed element-wise to result in a

new vector of the same length.

$$ \large{c =(a_1 × b_1, \, a_2 × b_2, \, a_3 × b_3)} $$

In [9]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3]) 
c = a * b
c

array([1, 4, 9])

#### Vector Division

Two vectors of equal length can be divided.
  
$$ \large{c = \frac{a}{b} $$

As with other arithmetic operations, this operation is performed element-wise

$$ c = \begin{pmatrix}
\frac{a_1}{b_1}, & \frac{a_2}{b_2}, & \frac{a_3}{a_4}\\
\end{pmatrix}$$
